#!/bin/sh

branchname=`git rev-parse --abbrev-ref HEAD`
issuetag="\${issue}"
if [ "$branchname" = "master" ]; then
    sed -i "s/$issuetag//" "$1"
else
    issue_num=`echo $branchname | sed -E 's/([[:digit:]]+).*/\1/'`
    sed -i "s/$issuetag/$issue_num/" "$1"
fi
