# -*- mode: sh -*-

# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

if [[ "$OSTYPE" == "darwin"* ]]; then
    . /opt/homebrew/opt/asdf/libexec/asdf.sh
    . /opt/homebrew/opt/asdf/etc/bash_completion.d/asdf.bash
fi
