set nocompatible  " be iMproved
filetype off " vundle required!
behave mswin

syntax on " syntax highlighting
set nu " line number
set ts=4
set sw=4
set softtabstop=4
set expandtab " tab을 space로 저장
set scrolloff=15 " scroll offset. 15줄 범위에서부터 scroll
set ruler " 현재 row, col을 출력
set autoindent
set cindent
set incsearch " incremental search
set hlsearch " 검색 결과 강조
set ignorecase " 대소문자 무시 검색
set smartcase " 대문자가 검색 문자열에 있을때는 noignorecase
set laststatus=2 " vim-powerline이 꾸며주는 상태바를 항상 출력하기 위해
" When off a buffer is unloaded when it is abandoned.
" argdo 명령으로 여러 파일을 변경할 수 있게
set hidden 

" sound, visual bell 둘 다 비활성화.
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" windows gvim에서 utf8로 인코딩 설정시 메시지가 깨져서 영문 메시지를 사용
set enc=utf-8
set fencs=ucs-bom,utf-8,cp949
set fenc=utf-8
if has("win32")
    " mac에서 명령어 인식을 못한다. 원인은 모르겠다.
	lang mes en

    " E303: Unable to open swap file for [No Name], recovery impossible
    " 방지하기 위해서 swap 파일을 저장할 디렉토리를 지정해 준다.
    " mac에서는 문제가 없으므로 win32에서만
    set directory=.,$TEMP
endif

" FIXME: 이렇게 무조건 절대 경로로 설정해야 하나? 
" vimrc 파일 위치를 기준으로 설정할 수 있는 방법은 없나?
set rtp+=~/.dotfiles/vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle' 
Bundle 'scrooloose/nerdtree'
Bundle 'Lokaltog/vim-powerline' 
Bundle 'tpope/vim-unimpaired'
Bundle 'tomtom/tcomment_vim'
Bundle 'guns/vim-clojure-static'
Bundle 'myusuf3/numbers.vim'
Bundle 'mhinz/vim-startify'
Bundle 'nelstrom/vim-markdown-preview'
" vundle http://kldp.org/node/125263 
" EasyMotion http://bit.ly/sXJJpS - navigation이 익숙해지기 전까지 막아둠
" tcomment http://goo.gl/KHx5V

if has('gui_running')
	set guioptions-=T " no toolbar
    set guioptions-=m " no memnubar
	" windows gvim에서 encoding을 utf-8로 설정하면 메뉴가 깨져서 langmenu를
	" 설정해 준다. 좀 무식해 보여...
	if has("win32")
		source $VIMRUNTIME/delmenu.vim
		set langmenu=ko_kr.utf-8
		source $VIMRUNTIME/menu.vim
	endif
endif

filetype plugin indent on " vundle required!

" Changing background color in vim at a certain column - stackoverflow
" http://goo.gl/whqKr
set cc=80
highlight ColorColumn ctermbg=lightgrey guibg=lightgrey

" ctrl-j 로 라인을 분리.
" http://goo.gl/qxOlY
nnoremap <NL> i<CR><ESC>

autocmd BufWinEnter *.{md,mkd,mkdn,mark*} silent setf markdown

if has("gui_macvim")
    set guifont=Menlo:h13
endif

