#!/bin/bash

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K'

function log_info { printf "${GREEN}[INFO] $1${NO_COLOR}\n"; }
function log_error { printf "${RED}[ERRO] $1${NO_COLOR}\n"; }

# 실행되는 쉘 절대 경로 구하기
# http://kldp.org/node/119861
cd ${0%/*} 2>/dev/null
shell_path=$PWD/${0##*/}

# TODO: 이거 한번에 하는 방법 없나?
script_path=${shell_path%/*}
root_path=${script_path%/*}

log_info "=> make symbolic links"

function safe_make_symbol_link {
    source=$1
    target=$2

    log_info "=> => make a symbol link: $source -> $target"

    if ! [ -e "$target" ]; then
        log_info "=> => => link"
        ln -s $source $target
    else
        log_error "=> => => skip: already exist $2"
    fi
}

safe_make_symbol_link $root_path/git/gitignore_global ~/.gitignore_global
safe_make_symbol_link $root_path/git/gitconfig ~/.gitconfig
safe_make_symbol_link $root_path/vim/vimrc ~/.vimrc
safe_make_symbol_link $root_path/vim/ideavimrc ~/.ideavimrc
safe_make_symbol_link $root_path/bash_profile ~/.bash_profile
safe_make_symbol_link $root_path/bashrc ~/.bashrc
safe_make_symbol_link $root_path/doom.d ~/.doom.d
safe_make_symbol_link $root_path/bin ~/bin
safe_make_symbol_link $root_path/bin.local ~/bin.local

log_info "=> set macOS defaults "

# finder에서 숨김 파일을 보게 한다
defaults write com.apple.finder AppleShowAllFiles -bool true;killall Finder
# 키 반복 입력 활성화
defaults write -g ApplePressAndHoldEnabled -bool false

log_info "=> homebrew"
if ! command -v brew > /dev/null; then
    log_info "=> => homebrew: installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
else
    log_info "=> => homebrew: already installed."
fi

log_info "=> => install bundle."
brew bundle --file $root_path/script/Brewfile
