#!/bin/bash

set -e

# 실행되는 쉘 절대 경로 구하기
# http://kldp.org/node/119861
cd ${0%/*} 2>/dev/null
shell_path=$PWD/${0##*/}

# TODO: 이거 한번에 하는 방법 없나?
script_path=${shell_path%/*}
root_path=${script_path%/*}

ln -s $root_path/git/gitignore_global ~/.gitignore_global
ln -s $root_path/git/gitconfig ~/.gitconfig
ln -s $root_path/vim/vimrc ~/.vimrc
ln -s $root_path/vim/ideavimrc ~/.ideavimrc
ln -s $root_path/bash_profile ~/.bash_profile
ln -s $root_path/bashrc ~/.bashrc

ln -s $root_path/doom.d ~/.doom.d
ln -s $root_path/bin ~/bin
ln -s $root_path/bin.local ~/bin.local

# finder에서 숨김 파일을 보게 한다
defaults write com.apple.finder AppleShowAllFiles -bool true;killall Finder
# 키 반복 입력 활성화
defaults write -g ApplePressAndHoldEnabled -bool false
