tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "railwaycat/emacsmacport"

# for doom emacs
brew "coreutils"
brew "autoconf"
brew "openssl@1.1"
brew "wxwidgets"
brew "libxslt"
brew "fop"
brew "asdf"
# for doom emacs
brew "fd"
brew "fontconfig"
brew "git"
brew "git-lfs"
brew "grep"
brew "mas"
brew "node"
brew "ripgrep"
brew "yt-dlp"
brew "railwaycat/emacsmacport/emacs-mac@28",
     args: ["with-modules", "with-native-compilation", "with-mac-metal"]

cask "alt-tab"
cask "iterm2"

mas "Amphetamine", id: 937984704
mas "Tailscale", id: 1475387142
mas "Amazon Kindle", id: 302584613
mas "Xcode", id: 497799835
